#!/bin/sh

foo=bar
echo "$foo"
# prints bar
echo '$foo'
# prints $foo

# $0 - 스크립트 이름
# $1 ~ $9 - 스크립트의 인자들. $1부터 첫번쨰 인자입니다.
# $@ - 모든 인자들
# $# - 인자의 수
# $? - 이전 명령을 반환하는 코드
# $$ - 현재 스크립트에 대한 프로세스 식별 번호 (PID)
# !! - 인수를 포함하여 마지막 명령 전체를 포함합니다. 일반적으로는 사용 권한이 누락되어 실패할 때 사용합니다. sudo를 함께 써서 실패한 명령을 신속하게 다시 실행할 수 있습니다.
# $_ - 마지막 명령에서 나온 마지막 인수입니다. 대화형 셸에 있는 경우 Esc를 입력한 후 .을 입력해 이 값을 신속하게 얻을 수 있습니다.

false || echo "Oops, fail"
# Oops, fail

true || echo "Will not be printed"
#

true && echo "Things went well"
# Things went well

false && echo "Will not be printed"
#

true ; echo "This will always run"
# This will always run

false ; echo "This will always run"
# This will always run